services:
  # Backend service
  - type: web
    name: ecom177-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ecom-app-1.0.0.jar --spring.profiles.active=prod
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecom177-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://ecom177-frontend.onrender.com

  # Frontend service  
  - type: web
    name: ecom177-frontend
    env: node
    buildCommand: cd ecom-frontend && npm install && npm run build
    startCommand: cd ecom-frontend && npm start
    staticPublishPath: ./ecom-frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ecom177-backend.onrender.com

databases:
  - name: ecom177-db
    databaseName: ecom177
    user: ecomuser